/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controladorbd;
import ModelJTableModel.ModeloTablaPagina;
import Modelo.Pagina;
import Utilidad.Utilidad;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class GestorSitiosWeb_IG extends javax.swing.JFrame implements Comuinicaciontablapagina {

    private Pagina pagina;
    private Utilidad utilidad;
    private gestionPagina gestionPagina;
    private Controladorbd controladorpagina;
    private ModeloTablaPagina tablaPagina;

    /**
     * Creates new form GestionPaginas
     */
    public GestorSitiosWeb_IG() {
        controladorpagina = new Controladorbd();
        tablaPagina = new ModeloTablaPagina(controladorpagina.obtenerlinkspaginas(), this);
        initComponents();
        //sirve para cambiar el icono del programa
        setIconImage(new ImageIcon(getClass().getResource("/iconos/internet.png")).getImage());
        utilidad = new Utilidad();
        gestionPagina = new gestionPagina(txtfecharegistro, txtnombrepagina, 
                txtlinkpagina, cbxtipoPagina, txtusuario, txtclave, utilidad, this);

        txtfecharegistro.setText(utilidad.fecha(new Date()));
        bneditar.setEnabled(false);
        bneliminar.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    public void guardar() {
        if (controladorpagina != null) {
            controladorpagina = new Controladorbd();
            controladorpagina.registrarLink(gestionPagina.guardar());
            JOptionPane.showMessageDialog(rootPane, "Sitio web guardado con éxito");
            tabla();
            gestionPagina.limpiar();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al guardar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    void editar() {
        // verifico que halla ingresado datos para editar
        if (gestionPagina == null) {
            JOptionPane.showMessageDialog(rootPane, "Error al editar el sitio web", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {

            Pagina paginaediatar = gestionPagina.guardar();
            paginaediatar.setIdPagina(pagina.getIdPagina());// obtengo el id del registro a editar

            if (controladorpagina.editar(paginaediatar)) {
                JOptionPane.showMessageDialog(rootPane, "Sitio web editado con éxito", "EDITADO", JOptionPane.INFORMATION_MESSAGE);
                tabla();
                gestionPagina.limpiar();
                bnguardar.setEnabled(true);
                bneditar.setEnabled(false);
                bneliminar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al editar el sitio web", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    void eliminar() {
        if (gestionPagina == null) {
            JOptionPane.showMessageDialog(rootPane, "Error al eliminar", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {

            Pagina paginaediatar = new Pagina();
            paginaediatar.setIdPagina(pagina.getIdPagina());// obtengo el id del registro a editar

            if (controladorpagina.eliminar(paginaediatar)) {
                JOptionPane.showMessageDialog(rootPane, "Sitio web eliminado con éxito del sistema", "ELIMINADO", JOptionPane.INFORMATION_MESSAGE);
                tabla();
                bnguardar.setEnabled(true);
                bneditar.setEnabled(false);
                bneliminar.setEnabled(false);
                gestionPagina.limpiar();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    void tabla() {
        List<Pagina> persona = controladorpagina.obtenerlinkspaginas();
        tablaPagina.setListaPagina(persona);
        tablaPagina.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfecharegistro = new javax.swing.JTextField();
        txtnombrepagina = new javax.swing.JTextField();
        txtlinkpagina = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        cbxtipoPagina = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        jCboxverclave = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        bnguardar = new javax.swing.JButton();
        bneditar = new javax.swing.JButton();
        bneliminar = new javax.swing.JButton();
        bnlimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtbusquedad = new javax.swing.JTextField();
        cmbbusquedad = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de links IG");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/dominio.png"))); // NOI18N
        jLabel1.setText("Gestor de Sitos web IG");

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nombre.png"))); // NOI18N
        jLabel2.setText("Nombre de la pagina");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calendario.png"))); // NOI18N
        jLabel3.setText("Fecha de registro");

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/enlace.png"))); // NOI18N
        jLabel4.setText("Link de la pagina");

        txtfecharegistro.setEditable(false);
        txtfecharegistro.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        txtfecharegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfecharegistroActionPerformed(evt);
            }
        });

        txtnombrepagina.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        txtnombrepagina.setToolTipText("Nombre de la página web");

        txtlinkpagina.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        txtlinkpagina.setToolTipText("Dirección de la página web");
        txtlinkpagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlinkpaginaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/categoria.png"))); // NOI18N
        jLabel5.setText("Tipo de pagina");

        txtusuario.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        txtusuario.setToolTipText("Usuario de página web");
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });

        cbxtipoPagina.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        cbxtipoPagina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Tienda Online", "Blog", "Institucionales o corporativas", "Noticias o revistas", "Redes Sociales", "Servicios", "Foros", "Wikis", "Multimedia", "Portfolios", "Streaming", "Juegos online" }));
        cbxtipoPagina.setToolTipText("Tipo de página web");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario.png"))); // NOI18N
        jLabel6.setText("Usuario");

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contrasena.png"))); // NOI18N
        jLabel7.setText("Contraseña");

        txtclave.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        txtclave.setToolTipText("Contraseña de página web");

        jCboxverclave.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jCboxverclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboxverclaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(202, 202, 202)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnombrepagina)
                    .addComponent(txtlinkpagina)
                    .addComponent(txtfecharegistro)
                    .addComponent(txtusuario)
                    .addComponent(cbxtipoPagina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCboxverclave)
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfecharegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombrepagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlinkpagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxtipoPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboxverclave)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable2.setModel(tablaPagina);
        jScrollPane2.setViewportView(jTable2);

        bnguardar.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        bnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disquete.png"))); // NOI18N
        bnguardar.setText("Guardar");
        bnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnguardarActionPerformed(evt);
            }
        });

        bneditar.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        bneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        bneditar.setText("Editar");
        bneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bneditarActionPerformed(evt);
            }
        });

        bneliminar.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        bneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        bneliminar.setText("Eliminar");
        bneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bneliminarActionPerformed(evt);
            }
        });

        bnlimpiar.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        bnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/escoba.png"))); // NOI18N
        bnlimpiar.setText("Limpiar");
        bnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnlimpiarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        jLabel8.setText("Buscar página");

        txtbusquedad.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        txtbusquedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedadKeyReleased(evt);
            }
        });

        cmbbusquedad.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        cmbbusquedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Nombre de la página", "Tipo de pagina" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(bnguardar)
                        .addGap(110, 110, 110)
                        .addComponent(bneditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bneliminar)
                        .addGap(97, 97, 97)
                        .addComponent(bnlimpiar)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(cmbbusquedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtbusquedad, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bneliminar)
                    .addComponent(bneditar)
                    .addComponent(bnguardar)
                    .addComponent(bnlimpiar))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbbusquedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbusquedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registro de links", jPanel1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/senal-de-informacion.png"))); // NOI18N
        jMenu2.setText("Acerca de ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfecharegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfecharegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfecharegistroActionPerformed

    private void txtlinkpaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlinkpaginaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlinkpaginaActionPerformed

    private void bnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnguardarActionPerformed
        guardar();
    }//GEN-LAST:event_bnguardarActionPerformed

    private void bnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnlimpiarActionPerformed
        gestionPagina.limpiar();
        bneditar.setEnabled(false);
        bneliminar.setEnabled(false);
        bnguardar.setEnabled(true);
    }//GEN-LAST:event_bnlimpiarActionPerformed

    private void bneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bneditarActionPerformed
        editar();
    }//GEN-LAST:event_bneditarActionPerformed

    private void bneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bneliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_bneliminarActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Acercade acerca = new Acercade(this, true);
        acerca.setVisible(true);


    }//GEN-LAST:event_jMenu2MouseClicked

    private void buscarPaginas() {
        System.out.println("Combo" + cmbbusquedad.getSelectedIndex());
        switch (cmbbusquedad.getSelectedIndex()) {
            case 1://Nombre
                tablaPagina.setListaPagina(controladorpagina.buscarPaginasnombre(txtbusquedad.getText()));
                tablaPagina.fireTableDataChanged();
                break;
            case 2://categoria
                tablaPagina.setListaPagina(controladorpagina.buscarPaginasCategoria(txtbusquedad.getText()));
                tablaPagina.fireTableDataChanged();
                break;
        }

    }
    private void txtbusquedadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedadKeyReleased
        buscarPaginas();
    }//GEN-LAST:event_txtbusquedadKeyReleased

    private void jCboxverclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboxverclaveActionPerformed
        if (jCboxverclave.isSelected()) {
            
            
            txtclave.setEchoChar((char)0);

        } else {
            txtclave.setEchoChar((char)1);
            

        }
    }//GEN-LAST:event_jCboxverclaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorSitiosWeb_IG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorSitiosWeb_IG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorSitiosWeb_IG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorSitiosWeb_IG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorSitiosWeb_IG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bneditar;
    private javax.swing.JButton bneliminar;
    private javax.swing.JButton bnguardar;
    private javax.swing.JButton bnlimpiar;
    private javax.swing.JComboBox<String> cbxtipoPagina;
    private javax.swing.JComboBox<String> cmbbusquedad;
    private javax.swing.JCheckBox jCboxverclave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtbusquedad;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtfecharegistro;
    private javax.swing.JTextField txtlinkpagina;
    private javax.swing.JTextField txtnombrepagina;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickPagina(Pagina p) {
        txtnombrepagina.setText(p.getNombrePagina());
        txtlinkpagina.setText(p.getLinkPagina());
        cbxtipoPagina.setSelectedItem(p.getTipoPagina());
        txtusuario.setText(p.getUsuario());
        txtclave.setText(utilidad.Desencriptadoclave(p.getClave()));
        pagina = p;
        bnguardar.setEnabled(false);
        bneditar.setEnabled(true);
        bneliminar.setEnabled(true);
        abrirEnlace(p);

    }

    int contadorClick = 0;
    boolean ejecutar;

// este metodo sirve para cuando se de dos click en la tabla este abra el enlace
    public void abrirEnlace(Pagina pd) {
        ejecutar = true;
        //HILO DE PROGRMACIÓN
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (ejecutar) {
                    try {
                        //Parar un segundo
                        Thread.sleep(1000);
                        contadorClick = 0;
                        ejecutar = false;
                        System.out.println("Reinicia CLICK");
                    } catch (InterruptedException e) {
                        System.out.println(e.getMessage());
                    }
                }
            }
        }).start();

        contadorClick++;
        if (contadorClick == 3) {
            if (JOptionPane.showConfirmDialog(rootPane, "Se abrira el enlace. Desea continuar",
                    "Se abrira el enlace", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                //esto sirve para abrir el enlace
                Desktop enlace = Desktop.getDesktop();
                String enlaceAcceder = pagina.getLinkPagina();
                try {
                    enlace.browse(new URI(enlaceAcceder));
                } catch (IOException | URISyntaxException e) {
                    e.getMessage();
                }
                contadorClick = 0;
                ejecutar = false;
            }

        }
        System.out.println("contadorClick" + contadorClick);
    }

}
